### ISSUE TITLE
"from backports import os" fails now?!

### ISSUE THREAD

**Issue by dankegel** [pjdelport/backports.os#11]
Caveat: I am a native guy, not a python guy.

On a freshly updated ubuntu 18.04 system, on a new account, try this:
```
$ pip install backports.os
$ python -c "from backports import os"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name os
```

This seems to have worked until today, and indeed, in accounts where backports.os was already installed a while ago, python -c "from backports import os" still works.  Did something change in the python 2.7 ecosystem?  Or am I just going insane?

**Comment by dankegel** [comment]
Wow.  "sudo apt remove python-configparser" seems to work around the problem.   And that package hasn't been updated lately.  

Why would uninstalling that package let python find backports.os?

**Comment by dankegel** [comment]
Aha, see https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1812589

**Comment by PiDelport** [comment]
This appears to be fixed by https://github.com/jaraco/configparser/issues/17.

Can this issue be closed?

**Comment by dankegel** [comment]
I... think so?  Thanks for asking.  I'm still unclear on how to check on whether the fix has propagated everywhere it should.

I filed https://bugs.launchpad.net/ubuntu/+source/configparser/+bug/1821247 to encourage Ubuntu to pull the fix into their package python-configparser.

**Comment by PiDelport** [comment]
Cool, thanks for filing that.
