### ISSUE TITLE
Add Licence file

### ISSUE THREAD

**Issue by Hooloovoo** [pjdelport/backports.os#3]
Sorry if I'm being daft, but I could not see what licence this code is released under. It would be great if you could please clarify with a licence file.

**Comment by PiDelport** [comment]
It's licensed under the [Python Software Foundation License](https://en.wikipedia.org/wiki/Python_Software_Foundation_License). At the moment, this is just specified in the `setup.py`, but a license file would be a good addition, yes!

**Comment by PiDelport** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add license files](https://trello.com/c/KENOTOu1/13-add-license-files)

**Comment by PiDelport** [comment]
PR #5 adds this.
